# Generated by Django 4.0.4 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_department_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(default='', max_length=100),
        ),
    ]
