# Generated by Django 4.0.4 on 2022-04-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
